/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.NewgenApi;

import java.util.Scanner;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PaymentApi {

	public static void main(String args[]) {
		SpringApplication.run(PaymentApi.class, args);
	}
}
